modLoader = "javafml"
loaderVersion = "[33,)"
license = "LGPLv3"
issueTrackerURL = ""
[[mods]]
modId = "riderdenier"
version = "1.0"
displayName = "Mod ID"
displayURL = ""
logoFile = "icon.png"
credits = ""
authors = "Corgi Taco"
description = '''
A simple mod to blacklist what mobs can be ridden per dimension!
'''
[[dependencies.riderdenier]]
modId = "forge"
mandatory = true
versionRange = "[33.0.0,)"
ordering = "NONE"
side = "BOTH"
